---
# tasks file for libvirt_infra

# Checks for VM hosts, OS and OS version requirements
- name: Preflight checks
  import_tasks: preflight_check.yml

# Installs libvirt packages basis python version
- name: Installing libvirt
  import_tasks: install_libvirt.yml

# Manages default and custom network and storage pool creation
- name: Libvirt network and storage pool configuration
  import_tasks: configure_libvirt.yml

