- name: Sending Ping to KVM hosts
  ping:
 
# Uses magic variables to test list of active hosts Vs total hosts targeted by the play
- name: Checking for targeted KVM hosts
  run_once: yes
  assert:
    that:
      - ansible_play_hosts == ansible_play_hosts_all
    msg: "The targeted Virtualization hosts could not be reached"
 
- name: Checking for targeted RHEL OS family
  assert:
    that:
      - ansible_os_family|lower == 'redhat'
    msg: "Targeted host needs to run RHEL, CentOS, Fedora"
 
- name: Checking for targeted Fedora version
  assert:
    that:
      - ansible_distribution_major_version|int >= 28
    msg: "Fedora major version should be greater than 28"
  when: ansible_distribution == "Fedora"
 
- name: Checking for targeted RHEL OS family version
  assert:
    that:
      - ansible_distribution_major_version|int >= 7
    msg: "RHEL or CentOS major version should >= 7"

- name: Getting CPU virtualization parameters
  shell: |
    set -o pipefail
    /usr/bin/grep -w -o -E 'svm|vmx' /proc/cpuinfo | /usr/bin/uniq
  args:
    executable: /bin/bash
  register: is_virt_capable
  changed_when: is_virt_capable.rc != 0
  # NOTE: pipefail and changed_when were added to address ansible-lint errors


- name: Checking if hardware virtualization has been turned on
  assert:
    that:
      - is_virt_capable.stdout == 'vmx' or is_virt_capable.stdout == 'svm'
    msg: "Please enable hardware virtualization in BIOS"

